apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
  labels:
    app: flaskdemo
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
        env: dev
    spec:
      containers:
      - name: flaskdemo
        image: prototypeacrdemo.azurecr.io/flaskdemo
        ports:
        - name:  http
          containerPort: 8080
          protocol: TCP