on:
  pull_request:
    branches:
    - main
name: Deploy to Containerized App Service
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      resourceGroupName: app-landingzone
      acrName: prototypedemoacr
      servicePlanName: container-appServicePlan
      appName: flaskdemoContainer
    steps:  
    - uses: actions/checkout@master

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{env.appName}} 
        app-settings-json: |
          [
              {
                  "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                  "value": "${{secrets.ACR_PASS}}",
                  "slotSetting": false
              },
              {
                  "name": "DOCKER_REGISTRY_SERVER_URL",
                  "value": "https://${{env.acrName}}.azurecr.io",
                  "slotSetting": false
              },
              {
                  "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                  "value": "${{env.acrName}}",
                  "slotSetting": false
              }
          ]

    # Deploy to Azure
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.appName}}
        images: ${{env.acrName}}.azurecr.io/${{env.appName}}:${{ github.sha }}      