on:
  push:
    branches:
    - main
name: Deploy Container App Landingzone
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      subscriptionId: a69ea5f4-a433-4459-aa84-c31759fa1d60
      regionLocation: westeurope
      resourceGroupName: containerapp-landingzone
      servicePlanName: container-appServicePlan
      appName: flaskdemo
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{env.subscriptionId}}
        region: ${{env.regionLocation}}
        template: ./app-landingzone.json
        parameters: appserviceplanName=${{env.servicePlanName}} siteName=${{env.appName}} resourceGroupName=${{env.resourceGroupName}} location=${{env.regionLocation}}
        