on:
  push:
    branches:
    - main
name: Deploy AKS Landingzone
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      subscriptionId: a69ea5f4-a433-4459-aa84-c31759fa1d60
      regionLocation: westeurope
      resourceGroupName: k8s-landingzone
      clusterName: k8s-cluster 
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{env.subscriptionId}}
        region: ${{env.regionLocation}}
        template: ./k8s-landingzone.json
        parameters: resourceName=${{env.clusterName}} location=${{env.regionLocation}} resourceGroupName=${{env.resourceGroupName}}
        